on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  eslint:
    runs-on: ubuntu-latest # Use the desired runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint ./src
